"""fixed

Revision ID: 49cd58e11b90
Revises: 2ebe31a12fc1
Create Date: 2025-11-03 16:17:43.114962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49cd58e11b90'
down_revision: Union[str, Sequence[str], None] = '2ebe31a12fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_responses', sa.Column('txt_file_path', sa.String(length=500), nullable=True))
    op.add_column('videos', sa.Column('channel_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'channel_id')
    op.drop_column('ai_responses', 'txt_file_path')
    # ### end Alembic commands ###
